copy 1_Rajayoga_EEG_Geo_InitializeTask.startupInfo 3_Rajayoga_EEG_Geo_Rest_PreTask.startupInfo   /y
copy 1_Rajayoga_EEG_Geo_InitializeTask.startupInfo 4_Rajayoga_EEG_Geo_ANGEL_LearnAndDo.startupInfo   /y
copy 1_Rajayoga_EEG_Geo_InitializeTask.startupInfo 5_Rajayoga_EEG_Geo_ANGEL_Whodunnit.startupInfo   /y
copy 1_Rajayoga_EEG_Geo_InitializeTask.startupInfo 6_Rajayoga_EEG_Geo_ANGEL_DiscernAndDecide.startupInfo   /y
copy 1_Rajayoga_EEG_Geo_InitializeTask.startupInfo 7_Rajayoga_EEG_Geo_Rest_PostTask.startupInfo   /y
copy 1_Rajayoga_EEG_Geo_InitializeTask.startupInfo 8_Rajayoga_EEG_Geo_LongMeditation.startupInfo   /y
