function [errorReturn] = NPhy_AppendERPConditions(ANGEL, subjectPrefix, erpNo, filesToBeAppended)
%NPhy_AppendERPConditions For each ERP, append all relevant conditions 
%
%   Using ERPLAB, appending the relevant conditions for an ERP into one file
%   Example: Frequent and Rare conditions as different bins in a P300 file
%
% Date of Creation: 19 Mar 2015
% Authors: Arun and Ajay
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Initialize variables
errorReturn = 0;

try

% Load .erp files 
[ERP, ALLERP] = pop_loaderp(...
        'filename', filesToBeAppended,...
        'filepath', ANGEL.erpAveragedDir, 'UpdateMainGui', 'off'); %#ok<*ASGLU>

% Append the averaged files
ERP = pop_appenderp(ALLERP, 'Erpsets', 1:length(filesToBeAppended));

% Do bin operations specific to each ERP
switch ANGEL.erpLabels{erpNo}

    case 'LRP'
        ERP = pop_binoperator(ERP, {...
            sprintf('LH = %i',...
                find(strcmpi(strrep({ERP.chanlocs.labels},...
                ' ',''),'C3'))),...
            sprintf('RH = %i',...
                find(strcmpi(strrep({ERP.chanlocs.labels},...
                ' ',''),'C4'))),...
            sprintf('nb1 = (b%i@LH + b%i@RH)/2 label Average Contra',...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightPress')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftPress'))),...
            sprintf('nb2 = (b%i@LH + b%i@RH)/2 label Average Ipsi',...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftPress')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightPress'))),...
            sprintf([...
                'nb3 = ((b%i@LH + b%i@RH)/2) -',...
                '((b%i@LH + b%i@RH)/2) ',...
                'label Average Contra Minus Ipsi'],...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightPress')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftPress')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftPress')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightPress'))),...
            });

    case 'N2pc'
        ERP = pop_binoperator(ERP, {...
            sprintf('LH = %i',...
                find(strcmpi(strrep({ERP.chanlocs.labels},...
                ' ',''),'PO7'))),...
            sprintf('RH = %i',...
                find(strcmpi(strrep({ERP.chanlocs.labels},...
                ' ',''),'PO8'))),...
            sprintf('nb1 = (b%i@LH + b%i@RH)/2 label Average Contra',...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightImage')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftImage'))),...
            sprintf('nb2 = (b%i@LH + b%i@RH)/2 label Average Ipsi',...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftImage')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightImage'))),...
            sprintf([...
                'nb3 = ((b%i@LH + b%i@RH)/2) -',...
                '((b%i@LH + b%i@RH)/2) ',...
                'label Average Contra Minus Ipsi'],...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightImage')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftImage')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'LeftImage')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'RightImage'))),...
            });

    case 'CD'
        ERP = pop_binoperator(ERP, {...
            sprintf('b%i = b%i - b%i label CDOn Minus ButtonPress',...
                ERP.nbin+1,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'CDOn')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'ButtonPress'))),...
            });                            

    case 'C1'
        ERP = pop_binoperator(ERP, {...
            sprintf('b%i = b%i - b%i label Top Minus Bottom',...
                ERP.nbin+1,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'Top')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'Bottom'))),...
            });   

    case 'ERN'
        ERP = pop_binoperator(ERP, {...
            sprintf('nb1 = (b%i+b%i)/2 label Correct',...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'Correct'))),...
            sprintf('nb2 = (b%i+b%i)/2 label Incorrect',...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'Incorrect'))),...
            }); 

    case 'P50'
        ERP = pop_binoperator(ERP, {...
            sprintf('b%i = b%i - b%i label StandardToneS1 Minus BlanktoneS1',...
                ERP.nbin+1,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'StandardToneS1')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BlankToneS1'))),...
            sprintf('b%i = b%i - b%i label StandardToneS2 Minus BlankToneS1',...
                ERP.nbin+2,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'StandardToneS2')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BlankToneS1'))),...
            });

    case 'MMN'
        ERP = pop_binoperator(ERP, {...
            sprintf('b%i = b%i - b%i label DeviantToneS1 Minus BlankToneS1',...
                ERP.nbin+1,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'DeviantToneS1')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BlankToneS1'))),...
            sprintf('b%i = b%i - b%i label StandardToneS1 Minus BlankToneS1',...
                ERP.nbin+2,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'StandardToneS1')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BlankToneS1'))),...
            sprintf('b%i = b%i - b%i label DeviantToneS1 Minus StandardToneS1',...
                ERP.nbin+3,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'DeviantToneS1')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'StandardToneS1'))),...
            }); 

    case 'N170'
        ERP = pop_binoperator(ERP, {...
            sprintf('b%i = b%i - b%i label FacePresent Minus BaselineImage',...
                ERP.nbin+1,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'FacePresent')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BaselineImage'))),...
            sprintf('b%i = b%i - b%i label FaceAbsent Minus BaselineImage',...
                ERP.nbin+2,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'FaceAbsent')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BaselineImage'))),...
            sprintf('b%i = b%i - b%i label ShapePresent Minus BaselineImage',...
                ERP.nbin+3,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'ShapePresent')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BaselineImage'))),...
            sprintf('b%i = b%i - b%i label ShapeAbsent Minus BaselineImage',...
                ERP.nbin+4,...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'ShapeAbsent')),...
                find(strcmpi(strrep(ERP.bindescr,' ',''),'BaselineImage'))),...
            });  

end  % End of switch for ERPs    

% Save the appended ERP file
% ERP specific Filtering
if ~isempty(regexpi(ANGEL.erpLabels{erpNo},'P50')) ||...
        ~isempty(regexpi(ANGEL.erpLabels{erpNo},'MMN'))
    ERP = pop_filterp(ERP, 1:ERP.nchan, 'Cutoff', 10,...
        'Design', 'fir', 'Filter', 'highpass', 'Order', 36);
end

ERP = pop_savemyerp(ERP,...
    'erpname', [subjectPrefix,'_',...
        ANGEL.erpLabels{erpNo}],...
    'filename',[subjectPrefix,'_',...
        ANGEL.erpLabels{erpNo},'.erp'],...
    'filepath', ANGEL.erpAppendedPerSubjectDir,...
    'Warning','on'); %#ok<*NASGU>


catch error
    warning('\nSkipped appending for the condition: %s for file:\n %s \n ******\n', ANGEL.erpEventLabelClusters{erpNo}{1}, filesToBeAppended{1});
    fprintf(ANGEL.logFileID,...
    '\n ******\nSkipped appending for the condition: %s for file: %s with error:\n %s\n ******\n',...
    ANGEL.erpEventLabels{erpNo},...
    filesToBeAppended{1}, error.message);
end

fprintf(ANGEL.logFileID,'\nCompleted appending erp conditions for : %s \n',filesToBeAppended{1});
end

